# src/Rapsys/PackBundle/Resources/config/parameters.yml
parameters:
    rapsys_pack:
        coutput: ~
        joutput: ~
        ioutput: ~
        cfilter: [ 'CPackFilter' ]
        jfilter: [ 'JPackFilter' ]
        ifilter: [ 'IPackFilter' ]
        prefix: ~
        scheme: ~
        timeout: 5
        user_agent: ~
        redirect: 3
    rapsys_pack.jpackfilter:
        bin: '/usr/local/bin/jpack'
    rapsys_pack.cpackfilter:
        bin: '/usr/local/bin/cpack'

framework:
    assets:
        packages:
            rapsys_pack:
                base_path: ~
                version: ~

# Force cache disable to regenerate resources each time
#twig:
#    cache: ~
