services:
    rapsys_pack.twig.pack_extension:
        class: Rapsys\PackBundle\Twig\PackExtension
        arguments: [ '@file_locator', '@service_container', '@assets.packages' ]
        tags: [ twig.extension ]
    rapsys_pack.twig.base64:
        class: Rapsys\PackBundle\Twig\Base64Extension
        tags: [ twig.extension ]
