#Routes configuration
rapsys_pack_map:
    path: '/map/{hash<[a-zA-Z0-9=_-]+>}/{updated<\d+>}/{latitude<\d+\.?\d*>}/{longitude<\d+\.?\d*>}/{zoom<\d+>?17}/{width<\d+>?640}/{height<\d+>?640}.{_format?jpeg}'
    controller: Rapsys\PackBundle\Controller\MapController::map
    methods: GET

rapsys_pack_multimap:
    path: '/multimap/{hash<[a-zA-Z0-9=_-]+>}/{updated<\d+>}/{latitude<\d+\.?\d*>}/{longitude<\d+\.?\d*>}/{coordinates<\d+(\.\d+)*,\d+(\.\d+)*(-\d+(\.\d+)*,\d+(\.\d+)*)*>}/{zoom<\d+>?15}/{width<\d+>?640}/{height<\d+>?640}.{_format?jpeg}'
    controller: Rapsys\PackBundle\Controller\MapController::multimap
    methods: GET
